### ISSUE TITLE
Error in W8.1 running xammp servr

### ISSUE THREAD

**Issue by gondwe** [2createStudio/shuttle-export#1]
Couldn't dump database: Couldn't export database: 'mysqldump' is not recognized as an internal or external command, o

perable program or batch file.

**Comment by mcbmcb0** [comment]
same error here in win 7-64, xampp, php 5.6.3. exception from dumper line 252 - no mysqldump. I've hacked it around a little and the 'Shuttle_Dumper_Native' class so far also won't write a file

**Comment by emohamed** [comment]
It's fixed in 4caff01e81a29fa8aa8e126a65c4fba9f968a9fb

**Comment by mcbmcb0** [comment]
thanks!
now works on win7-64/ xampp / php 5.6 and debian jessie / php 5.6.17
