### ISSUE TITLE
File name and export directory

### ISSUE THREAD

**Issue by rastynails** [2createStudio/shuttle-export#2]
Thanks a lot for the nice script. I'm using your script for hourly backups where I need to change the dump file name manually so the new dump file won't overwrite the old file.

I  usually use the below command in cron jobs and I get file name with date and time.
/usr/bin/mysqldump -u username -ppassword database_name | gzip > /path/filename-`date +\%Y-\%m-\%d-\%H.\%M.\%S`.sql.gz

1- How can I get file name with date and time using your script?
2- How to choose the different export location instead of storing the dumped files in same directory as where is the script is?

Thank you very much

**Comment by emohamed** [comment]
This is a PHP utility, so you should do this those things though PHP.

> 1- How can I get file name with date and time using your script?

Use the `date()` PHP function. Read more about it [here](http://php.net/manual/en/function.date.php).

> 2- How to choose the different export location instead of storing the dumped files in same directory as where is the script is?

The `dump` method accepts arbitrary paths. It uses the current working directory only when the provided path is not absolute. 

## 

Here is an example code that should get you started:

``` php
$dumper = Shuttle_Dumper::create(array(
    'host' => '',
    'username' => 'user',
    'password' => 'pass',
    'db_name' => 'db_name',
));
$dump_location = '/path/filename-' . date('Y-m-d-H.m.s') . '.sql.gz';
$dumper->dump($dump_location);

```

**Comment by rastynails** [comment]
Thank you very much for your response. It worked great :)
